[build]
  publish = "build"
  command = "yarn build"
[build.environment]
  NODE_VERSION = "15"
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--no-ignore-optional"
  REACT_APP_API_ENDPOINT = "https://wkubgjbrr2.execute-api.us-east-1.amazonaws.com/"
  REACT_APP_GEOJSON_ENDPOINT = "https://raw.githubusercontent.com/childpovertyactionlab/cpal-evictions/main/"
[context.production.environment]
  REACT_APP_API_ENDPOINT = "https://faxkuv0im9.execute-api.us-east-1.amazonaws.com/"
  REACT_APP_GEOJSON_ENDPOINT = "https://raw.githubusercontent.com/childpovertyactionlab/cpal-evictions/production/"
